"""Explanations of implemented Nour features, separate from market decisions."""
CAPABILITIES = [
    ('navigation', 'Pages et exports', 'Comment télécharger les données ADI ?'),
    ('market', 'MASI et séance', 'Combien de valeurs montent et baissent ?'),
    ('chart', 'Graphiques et indicateurs visuels', 'Comment zoomer et lire les bougies ?'),
    ('technical', 'Indicateurs techniques', 'Quelle activité et quelle variation sur 20 séances pour ADI ?'),
    ('fundamentals', 'Comptes annuels et semestriels', 'Quel chiffre d’affaires et quel résultat pour JET ?'),
    ('score', 'Score et facteurs', 'Comment est calculé le score de ADI ?'),
    ('statistics', 'Fréquences historiques', 'Statistiques ADI sur 20 séances et intervalle de Wilson ?'),
    ('liquidity', 'Liquidité et capacité de sortie', 'Combien de séances pour sortir du scénario ADI ?'),
    ('risk', 'Risque face au MASI', 'Quelle volatilité et quelle baisse maximale pour ADI ?'),
    ('sector', 'Comparables comptables', 'Compare ADI aux autres titres de son secteur'),
    ('laboratory', 'Laboratoire après frais', 'Laboratoire ADI sur 20 séances avec 1 % achat et 1 % vente'),
    ('news', 'Radar de publications', 'Quelles actualités officielles pour JET ?'),
    ('macro', 'Macro et international', 'Quel prix du Brent et quelle date de source ?'),
    ('briefing', 'Briefings et éditions', 'Résume le briefing de clôture'),
    ('quality', 'Qualité et collecte', 'Pourquoi les données CMT sont limitées ?'),
    ('assistant', 'Assistant, ECC et limites', 'À quoi sert ECC et y a-t-il une IA générative ?'),
]

DEFINITIONS = {
    'per': 'PER = cours / BPA annuel. Il exprime combien le cours représente de fois ce bénéfice. Un PER faible ne prouve pas une bonne affaire; vérifier le périmètre, le capital et les éléments exceptionnels.',
    'bpa': 'BPA = résultat annuel retenu / nombre d’actions documenté. Une moyenne pondérée n’est revendiquée que si elle est publiée; un nombre de clôture donne un BPA indicatif. Un semestre n’est pas doublé.',
    'pb': 'P/B = cours / capitaux propres par action. Utiliser la part du groupe pour des comptes consolidés, ou les fonds propres sociaux pour des comptes sociaux; pas le total avec minoritaires à la place du groupe.',
    'roe': 'ROE Nour = résultat annuel / capitaux propres de clôture × 100. Ce n’est pas un ROE sur fonds propres moyens.',
    'pnb': 'Le produit net bancaire mesure l’activité bancaire ou financière selon les comptes publiés. Il reste distinct du chiffre d’affaires; aucune dette/EBITDA industriel n’est appliquée aux établissements financiers.',
    'rnpg': 'RNPG signifie résultat net part du groupe : il exclut le résultat attribué aux minoritaires. Un résultat total consolidé ne le remplace pas.',
    'debt': 'La dette nette stricte Nour est la dette financière moins la trésorerie-actif documentée, hors placements et comptes associés. La comparer à l’EBE exige des périmètres compatibles; l’indisponibilité reste visible.',
    'rsi': 'Le RSI 14 compare gains et pertes des clôtures avec le lissage de Wilder sur 14 séances. 0 à 100 décrit le momentum passé; un RSI bas n’annonce pas automatiquement un rebond.',
    'mm': 'Une moyenne mobile simple est la moyenne des clôtures sur le nombre de séances indiqué. Les fiches proposent 20, 50 et 200 séances; le graphique propose MM20 et MM50. Les trous ne sont pas comblés.',
    'macd': 'MACD = moyenne exponentielle 12 séances moins moyenne exponentielle 26 séances. Le signal est sa moyenne exponentielle 9 séances. Le graphique utilise l’historique chargé, pas seulement le dernier point.',
    'bollinger': 'Les bandes de Bollinger du graphique entourent la moyenne 20 séances à plus et moins deux écarts-types des clôtures. Elles décrivent la dispersion passée; elles ne garantissent aucune borne future.',
    'atr': 'ATR 14 Nour = moyenne simple des 14 amplitudes vraies : maximum entre haut−bas, écart haut−clôture précédente et écart bas−clôture précédente. C’est une amplitude en MAD, pas une direction ni l’ATR lissé de Wilder.',
    'levels': 'Support et résistance des fiches = minimum des bas et maximum des hauts des 20 séances précédentes, hors dernière bougie. Sur le MASI, le briefing utilise des clôtures historiques, pas des extrêmes intrajournaliers. Un niveau déjà rompu est une référence à reconquérir, pas un support confirmé.',
    'activity': 'L’activité technique compare la quantité de la dernière séance à la médiane des 20 quantités précédentes. Ce n’est pas le montant MAD. Un gros échange n’identifie pas son acheteur ni un flux institutionnel.',
    'liquidity': 'Sur au plus 20 séances récentes, Nour utilise les séances actives et leurs médianes. Le montant historique est estimé par clôture × quantité, distinct du montant réel de dernière séance. La capacité hypothétique est 10 % de la quantité médiane; le scénario par défaut porte sur 1 000 titres. Il exige au moins 10 séances actives et des données fiables; ce n’est pas une promesse d’exécution.',
    'beta': 'Le bêta historique mesure la sensibilité des rendements du titre à ceux du MASI, par covariance / variance du MASI. Les dates adjacentes sont appariées exactement, sur 253 séances MASI et au moins 60 rendements; un bêta ne prédit pas la prochaine séance.',
    'correlation': 'La corrélation de Pearson mesure la coévolution passée, entre −1 et +1, sur les mêmes dates appariées. Elle n’établit pas de causalité.',
    'volatility': 'La volatilité annualisée de risque utilise l’écart-type des rendements quotidiens appariés × racine de 252. Celle de tendance porte sur 20 rendements. Ce sont des horizons distincts; un chiffre plus élevé décrit davantage de fluctuations passées.',
    'drawdown': 'La baisse maximale décrit la pire baisse depuis un sommet jusqu’à un creux de la fenêtre. Nour exige une fenêtre complète pour l’afficher; elle ne limite pas une perte future.',
    'statistics': 'Les fréquences de la fiche sont inconditionnelles, sur rendements non chevauchants de 1, 5 ou 20 observations historiques. Moins de 30 cas : fréquence indisponible. Hors dividendes et frais; elles ne sont pas les résultats conditionnels du laboratoire.',
    'wilson': 'L’intervalle de Wilson à 95 % donne une plage indicative autour de la fréquence observée, liée à l’effectif. Il ne corrige ni la dépendance temporelle ni les changements de régime, et ne mesure pas la chance d’une hausse demain.',
    'percentile': 'La médiane est le résultat du milieu. Les percentiles 10 et 90 situent les résultats observés; ils ne garantissent aucune borne future. Dans le secteur, le percentile croissant est un rang descriptif parmi des pairs compatibles, pas une note de qualité.',
    'sector': 'Les comparables exigent le même secteur, exercice, MAD, périmètre et norme comptable identifiée, un titre observable et au moins trois autres ratios utilisables. La médiane exclut le titre examiné. Une population insuffisante laisse la comparaison indisponible.',
    'score': 'Le score descriptif combine tendance20 (20 points de poids), tendance50 (15), RSI (15), activité (10), liquidité (20) et ROE (20). La somme des points obtenus est divisée par la somme des poids disponibles puis multipliée par 100. La couverture reste affichée; en dessous de 70 % ou hors état observable, la note partielle est masquée. PER, dette, semestres, actualités et IA ne contribuent pas directement à cette version.',
    'archive': 'Nour conserve la première observation réelle quotidienne du score, avec heure, version et empreinte des entrées. Elle n’est ni réécrite ni remplie dans le passé. Un historique de cours de trois ans n’est pas un historique de scores publiés; aucune efficacité prospective du score n’est encore validée.',
    'laboratory': 'Le laboratoire rejoue clôture supérieure aux MM20 et MM50 à des dates fixes, puis entrée à la clôture suivante et sortie 5, 20 ou 60 séances MASI plus tard. Les rendements d’un même titre/horizon ne chevauchent pas. Filtres : période 2023–2024 ou depuis 2025, MASI au-dessus ou sous MM200 au signal. Entrées/sorties ou fenêtres nécessaires manquantes et frontières de capital/reprise sont exclues. Ce n’est ni le score rejoué ni un test hors échantillon intact.',
    'costs': 'Dans le laboratoire : rendement net = sortie × (1−frais vente−glissement) / [entrée × (1+frais achat+glissement)] − 1. Les champs acceptent 0 à 10 % par côté, défaut 1 % achat, 1 % vente, 0 % glissement. Le MASI de comparaison reste brut. Dividendes, fiscalité, carnet et exécution réelle ne sont pas simulés.',
    'news': 'Le radar stocke titre, lien, source, date et classement; pas le corps complet des articles. S1 signifie présence officielle repérée, pas validation des chiffres. Une alerte presse S2 ou un relais Google News reste à recouper. Aucun sentiment ni impact de nouvelle n’entre dans le score.',
    'macro': 'Douze références internationales sont collectées auprès du scanner public TradingView. Les futures ne sont pas des prix spot; USD/MAD et EUR/MAD ne sont pas des fixings BAM. Dates et délais diffèrent. Une collecte défaillante garde l’archive et sa date originale. Aucun PIB, taux directeur ou chiffre d’inflation n’est extrait des titres du radar.',
    'quality': 'OBSERVABLE décrit des données exploitables, LIMITÉ des données ou une liquidité insuffisantes, INDISPONIBLE un cours absent/ancien/incohérent, SUSPENDU une suspension. Ce sont des statuts de données, pas ACHETER/VENDRE. Les jours sans transaction et la séance annulée du 17/09/2026 ne créent pas de bougies.',
    'intraday': 'Avant 16 h, un relevé CDG du jour datant d’au plus 30 minutes peut être présenté provisoire. Il reste distinct des clôtures, du graphique historique et du score. Le cutoff du collecteur ne prouve pas la clôture officielle; après expiration, l’archive ne devient pas une cotation fraîche.',
    'collection': 'Cinq collectes ouvrées sont programmées à 09:45, 11:46, 13:45, 15:45 et 18:00, heure de Casablanca. Les éditions matin, midi et clôture sont séparées. GitHub peut retarder ou manquer un lancement; l’heure réelle et les états des collecteurs priment.',
    'chart': 'Le graphique propose plages de dates, zoom, déplacement, courbe ou bougies, lecture au pointeur et aux flèches du clavier, MM20/MM50, Bollinger, RSI, MACD et volumes. Les overlays visuels ne changent pas le score. Le MASI ne possède pas de faux OHLC de titre. Les CSV sont accessibles sur les fiches.',
    'sectors': 'Nour sépare PNB et CA, résultat groupe et total, fonds propres groupe et totaux. Pour les banques et sociétés financières, pas de dette/EBITDA industriel; pour l’industrie et le BTP, lire marge, dette et trésorerie selon les comptes; pour assurance, réserves et périmètre de fusion. Les points sectoriels du briefing sont des éléments à examiner, pas des ratios inventés.',
    'assistant': 'Le mode public est un lecteur déterministe des données et méthodes implémentées, sans IA générative. Une passerelle LLM explicative est préparée mais aucun modèle n’est activé ici. Les échanges restent dans la page; aucun ordre, clé API ou modification de score. ECC fournit huit compétences et trois profils de revue figés pour le développement; ce n’est ni un modèle ni un moteur de trading.',
    'limits': 'Nour ne dispose pas d’un carnet d’ordres, spread réellement mesuré, identification Smart Money, prévision de cours, probabilité validée de prochaine séance, PER global historique, ROIC ni validation prospective du score. Une source documentaire présente ne certifie pas tous ses chiffres. Le moteur principal reste indépendant et n’est jamais modifié.',
}


def knowledge():
    return {'version': 'nour-help-v1', 'capabilities': [dict(id=i, label=l, example=e) for i,l,e in CAPABILITIES],
            'definitions': dict(DEFINITIONS)}
